### ISSUE TITLE
[어드민] 게시글 관리 페이지 구현

### ISSUE THREAD

**Issue by qnfzksla** [qnfzksla/board-admin#32]
## Todo
* [x] 게시판 프로젝트
    * [x] API 호출이 가능하도록 인증 설정 변경하기
    * [x] Data REST API 설정 검토하기
    * [x] 테스트용 계정 추가하기
* [x] 게시글, 댓글 살세 내용을 보기 위한 모달 추가
* [x] 기본 에러 페이지 구현

## Reference
* #28
